### ISSUE TITLE
Allocation form is not saving data properly in some cases

### ISSUE THREAD

**Issue by otech47** [setlife-network/trinary#488]
Something similar is still happening here:

https://www.loom.com/share/685f2a8e80c74d83952041c6a0645050

Not sure if we should re-open this or create a new issue @sofiarm21 but maybe it's the same fix in a different component?

_Originally posted by @otech47 in https://github.com/setlife-network/trinary/issues/372#issuecomment-887923468_

Additional details:

https://www.loom.com/share/32569ec948784f608dd9e2d0cf098798

**Comment by otech47** [comment]
@Ovifer13 maybe some of this is fixed/addressed in some of the open PRs but would like to just do thorough testing to make sure these little things don't happen

**Comment by Ovifer13** [comment]
> @Ovifer13 maybe some of this is fixed/addressed in some of the open PRs but would like to just do thorough testing to make sure these little things don't happen

I have not noticed this error before but I will do some tests on the opened PRs to check.

**Comment by Ovifer13** [comment]
**Update**
After testing the others PRs I notice that this issue is not fixed yet.
